import type { Metadata } from "next";
import BrowserSanitizer from "@/components/BrowserSanitizer";
import { Toaster } from "@/components/ui/sonner";
import ThemeProviderWrapper from "@/components/ThemeProviderWrapper";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#2563eb" />
      </head>
      <body suppressHydrationWarning className={`antialiased theme-primary`}>
        {/* Remove extension-injected attributes that can cause hydration mismatch */}
        <ThemeProviderWrapper>
          <BrowserSanitizer />
          {/* Navbar scoped to dashboard */}
          {children}
          <Toaster />
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
