#!/bin/bash

###############################################################################
# Encryption Script for global.config.ts
# This script encrypts the global.config.ts file using a key derived from:
# - API_KEY
# - JWT_EXPIRATION  
# - JWT_SECRET
# 
# It then generates a secure version: global-secure.config.ts
# 
# Usage: ./encrypt-config.sh
###############################################################################

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# File paths
ENV_FILE="${SCRIPT_DIR}/.env"
CONFIG_FILE="${SCRIPT_DIR}/src/Common/config/global.config.ts"
SECURE_CONFIG_FILE="${SCRIPT_DIR}/src/Common/config/global-secure.config.ts"
NODE_SCRIPT="${SCRIPT_DIR}/encrypt-config.js"

# Check if .env file exists
if [ ! -f "$ENV_FILE" ]; then
    echo "❌ Error: .env file not found at $ENV_FILE"
    exit 1
fi

# Check if config file exists
if [ ! -f "$CONFIG_FILE" ]; then
    echo "❌ Error: global.config.ts file not found at $CONFIG_FILE"
    exit 1
fi

# Extract environment variables from .env
extract_env() {
    local key=$1
    grep "^${key}=" "$ENV_FILE" | cut -d'=' -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
}

API_KEY=$(extract_env "API_KEY")
JWT_EXPIRATION=$(extract_env "JWT_EXPIRATION")
JWT_SECRET=$(extract_env "JWT_SECRET")

# Validate that all required environment variables are set
if [ -z "$API_KEY" ] || [ -z "$JWT_EXPIRATION" ] || [ -z "$JWT_SECRET" ]; then
    echo "❌ Error: Missing required environment variables:"
    [ -z "$API_KEY" ] && echo "  - API_KEY"
    [ -z "$JWT_EXPIRATION" ] && echo "  - JWT_EXPIRATION"
    [ -z "$JWT_SECRET" ] && echo "  - JWT_SECRET"
    exit 1
fi

echo "🔐 Starting encryption process..."
echo "📄 Source file: $CONFIG_FILE"

# Create a Node.js script to perform the encryption and save to .env
cat > "$NODE_SCRIPT" << 'NODEJS_EOF'
const fs = require('fs');
const crypto = require('crypto');
const path = require('path');
const readline = require('readline');

// Get arguments
const configFile = process.argv[2];
const envFile = process.argv[3];
const apiKey = process.argv[4];
const jwtExpiration = process.argv[5];
const jwtSecret = process.argv[6];

try {
  // Generate encryption key from combined secret
  const combined = apiKey + jwtSecret + jwtExpiration;
  const key = crypto.createHash('sha256').update(combined).digest();

  // Read the config file
  const configContent = fs.readFileSync(configFile, 'utf8');

  // Parse the config file to extract variable names and values
  // Match pattern: export const VariableName = "...string..." or '...string...' or number or boolean
  const varPattern = /export\s+const\s+(\w+)\s*=\s*(['"]?)([^;]+?)\2(?=\s*;)/g;
  let match;
  const encryptedVars = {};

  while ((match = varPattern.exec(configContent)) !== null) {
    const varName = match[1];
    let value = match[3].trim();
    
    // Generate random IV for each value
    const iv = crypto.randomBytes(16);
    
    // Create cipher
    const cipher = crypto.createCipheriv('aes-256-cbc', key, iv);
    
    // Encrypt the content
    let encrypted = cipher.update(value, 'utf8', 'base64');
    encrypted += cipher.final('base64');
    
    // Combine IV and encrypted data
    const ivBase64 = iv.toString('base64');
    const encryptedData = ivBase64 + ':' + encrypted;
    
    encryptedVars[varName] = encryptedData;
  }

  // Read existing .env file to preserve other variables
  let envContent = '';
  if (fs.existsSync(envFile)) {
    envContent = fs.readFileSync(envFile, 'utf8');
  }

  // Parse existing .env file and remove old encrypted variables
  const envLines = envContent.split('\n');
  const preservedLines = [];
  let inEncryptedSection = false;

  for (const line of envLines) {
    const trimmed = line.trim();
    // Skip empty lines and comments in the encrypted section
    if (trimmed.startsWith('# Encrypted configuration')) {
      inEncryptedSection = true;
      continue;
    }
    if (inEncryptedSection && (trimmed.startsWith('ENCRYPTED_') || trimmed === '')) {
      continue;
    }
    if (inEncryptedSection && trimmed && !trimmed.startsWith('ENCRYPTED_')) {
      inEncryptedSection = false;
    }
    if (trimmed || !inEncryptedSection) {
      preservedLines.push(line);
    }
  }

  // Remove trailing empty lines
  while (preservedLines.length > 0 && preservedLines[preservedLines.length - 1].trim() === '') {
    preservedLines.pop();
  }

  // Build final .env content
  const newEnvLines = preservedLines;
  newEnvLines.push('');
  newEnvLines.push('# Encrypted configuration values (auto-generated by encrypt-config.sh)');
  
  for (const [varName, encryptedValue] of Object.entries(encryptedVars)) {
    // Convert varName to UPPERCASE (e.g., ApiUrl -> APIURL, Port -> PORT)
    const uppercasedVarName = varName.toUpperCase();
    newEnvLines.push(`ENCRYPTED_${uppercasedVarName}=${encryptedValue}`);
  }

  const finalEnvContent = newEnvLines.join('\n');
  fs.writeFileSync(envFile, finalEnvContent, 'utf8');
  
  console.log('✅ Configuration encrypted and saved to .env!');
  console.log('📝 Encrypted variables added (accessible via process.env):');
  for (const varName of Object.keys(encryptedVars)) {
    const uppercasedVarName = varName.toUpperCase();
    console.log(`  - process.env.ENCRYPTED_${uppercasedVarName}`);
  }
  console.log('🔑 Encryption key: SHA-256(API_KEY + JWT_SECRET + JWT_EXPIRATION)');
  
} catch (error) {
  console.error('❌ Process failed:', error.message);
  process.exit(1);
}
NODEJS_EOF

# Execute Node.js script with env vars loaded
export API_KEY JWT_EXPIRATION JWT_SECRET
node "$NODE_SCRIPT" "$CONFIG_FILE" "$ENV_FILE" "$API_KEY" "$JWT_EXPIRATION" "$JWT_SECRET"

# Generate global-secure.config.ts dynamically using Node.js
cat > "${SCRIPT_DIR}/generate-secure-config.js" << 'GENERATE_SECURE_EOF'
const fs = require('fs');

const envFile = process.argv[2];
const secureConfigFile = process.argv[3];

try {
  // Read .env file
  const envContent = fs.readFileSync(envFile, 'utf8');
  
  // Extract all ENCRYPTED_* variables
  const encryptedVars = [];
  envContent.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (trimmed.startsWith('ENCRYPTED_') && trimmed.includes('=')) {
      const [key] = trimmed.split('=');
      encryptedVars.push(key);
    }
  });

  // Generate TypeScript file
  let tsContent = `import { encryptionUtility } from '../utilities/encryption.utility';

/**
 * Secure configuration with automatic decryption
 * All encrypted values are read from environment variables and automatically decrypted
 * Environment variables are generated by encrypt-config.sh in format: ENCRYPTED_VARIABLE_NAME
 */

// Export decrypted values from environment variables
`;

  for (const envVar of encryptedVars) {
    // Remove ENCRYPTED_ prefix to get original variable name
    const varName = envVar.substring('ENCRYPTED_'.length);
    
    // Convert APIURL -> ApiUrl, PORT -> Port
    const exportVarName = 'Encrypted_' + varName
      .split('_')
      .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
      .join('_');
    
    tsContent += `export const ${exportVarName} = process.env.${envVar}
  ? encryptionUtility.decrypt(process.env.${envVar})
  : undefined;

`;
  }

  fs.writeFileSync(secureConfigFile, tsContent, 'utf8');
  console.log('✨ Generated: ' + secureConfigFile);
  console.log('📝 Exported variables:');
  for (const envVar of encryptedVars) {
    const varName = envVar.substring('ENCRYPTED_'.length);
    const exportVarName = 'Encrypted_' + varName
      .split('_')
      .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
      .join('_');
    console.log(`  - ${exportVarName}`);
  }
} catch (error) {
  console.error('❌ Failed to generate secure config:', error.message);
  process.exit(1);
}
GENERATE_SECURE_EOF

node "${SCRIPT_DIR}/generate-secure-config.js" "$ENV_FILE" "$SECURE_CONFIG_FILE"
rm -f "${SCRIPT_DIR}/generate-secure-config.js"
