import { encryptionUtility } from '../utilities/encryption.utility';

/**
 * Secure configuration with automatic decryption
 * All encrypted values are read from environment variables and automatically decrypted
 * Environment variables are generated by encrypt-config.sh in format: ENCRYPTED_VARIABLE_NAME
 */

// Export decrypted values from environment variables
export const Encrypted_Apiurl = process.env.ENCRYPTED_APIURL
  ? encryptionUtility.decrypt(process.env.ENCRYPTED_APIURL)
  : undefined;

export const Encrypted_Port = process.env.ENCRYPTED_PORT
  ? encryptionUtility.decrypt(process.env.ENCRYPTED_PORT)
  : undefined;
